packages/react-impression/src/components/Progress/Progress.js, packages/react-impression/src/components/Progress/README.md
=> Update docs of progress

packages/react-impression/src/components/Alert/Alert.js, packages/react-impression/src/components/Alert/README.md, packages/react-impression/styleguide.config.js
=> Docs alert

packages/react-impression/src/components/Radio/README.md, packages/react-impression/src/components/Radio/Radio.js, packages/react-impression/src/components/RadioGroup/README.md, packages/react-impression/src/components/RadioGroup/RadioGroup.js
=> Update docs of component Radio and RadioGroup

.gitignore, packages/react-impression/src/components/Loading/Loading.js, packages/react-impression/src/components/Loading/README.md, packages/react-impression/src/components/LoadingAddon/LoadingAddon.js, packages/react-impression/src/components/LoadingAddon/README.md
1. 修改了.gitignore
2. 添加Loading组件的实例
3. 修改Loading和LoadingAddon的注释
=> Docs loading

packages/react-impression/src/components/Modal/Modal.js, packages/react-impression/src/components/Modal/README.md, packages/react-impression/src/components/ModalBody/ModalBody.js, packages/react-impression/src/components/ModalFooter/ModalFooter.js, packages/react-impression/src/components/ModalHeader/ModalHeader.js
=> Docs Modal

packages/react-impression/src/components/Confirm/Confirm.js, packages/react-impression/src/components/Confirm/README.md
=> [ADD] Confirm

packages/react-impression/src/components/Collapse/Collapse.js, packages/react-impression/src/components/CollapseBody/CollapseBody.js, packages/react-impression/src/components/CollapseTitle/CollapseTitle.js
=> [ADD] Collapse

packages/react-impression/src/components/Breadcrumb/Breadcrumb.js, packages/react-impression/src/components/Breadcrumb/README.md
=> [ADD] Breadcrumb

packages/react-impression/src/components/Flex/Flex.js, packages/react-impression/src/components/Flex/README.md, packages/react-impression/src/components/FlexItem/FlexItem.js, packages/react-impression/src/components/FlexItem/README.md
- 更新flex文档及例子
- 更新flexItem文档及例子
=> [FIX] flex和flexItem

packages/react-impression/src/components/Col/Col.js, packages/react-impression/src/components/Col/README.md, packages/react-impression/src/components/Row/README.md, packages/react-impression/src/components/Row/Row.js
=> Update docs of component Row and Col

packages/react-impression/src/components/Button/Button.js, packages/react-impression/src/components/Button/README.md, packages/react-impression/src/components/ButtonGroup/ButtonGroup.js, packages/react-impression/src/components/ButtonGroup/README.md, packages/react-impression/src/components/ButtonToolbar/ButtonToolbar.js, packages/react-impression/src/components/ButtonToolbar/README.md
button buttonGroup buttonToolbar
=> Docs button

packages/react-impression/src/components/Container/Container.js, packages/react-impression/src/components/Content/Content.js
=> [ADD] Container Content

packages/react-impression/src/components/Image/Image.js, packages/react-impression/src/components/Image/README.md
=> Docs image

packages/react-impression/src/components/Checkbox/Checkbox.js, packages/react-impression/src/components/Checkbox/README.md, packages/react-impression/src/components/CheckboxGroup/CheckboxGroup.js, packages/react-impression/src/components/CheckboxGroup/README.md
=> [ADD] Checkbox

packages/react-impression/src/components/Card/Card.js, packages/react-impression/src/components/Card/README.md, packages/react-impression/src/components/CardBlock/CardBlock.js, packages/react-impression/src/components/CardBlock/README.md, packages/react-impression/src/components/CardFooter/CardFooter.js, packages/react-impression/src/components/CardFooter/README.md, packages/react-impression/src/components/CardHeader/CardHeader.js, packages/react-impression/src/components/CardHeader/README.md
=> [ADD] Card--Block--Footer--Header

packages/react-impression/src/components/InlineSelect/InlineSelect.js, packages/react-impression/src/components/InlineSelect/README.md, packages/react-impression/src/components/InlineSelectOption/InlineSelectOption.js, packages/react-impression/src/components/InlineSelectOption/README.md
提交修改内容
- inlineSelect
- inlineSelectOption
=> [ADD] inlineSelect组件

packages/react-impression/src/components/Input/Input.js, packages/react-impression/src/components/Input/README.md, packages/react-impression/src/components/InputGroup/InputGroup.js, packages/react-impression/src/components/InputGroup/README.md, packages/react-impression/src/components/InputGroupAddon/InputGroupAddon.js, packages/react-impression/src/components/InputGroupAddon/README.md, packages/react-impression/src/components/InputGroupButton/InputGroupButton.js, packages/react-impression/src/components/InputGroupButton/README.md, packages/react-impression/src/components/InputGroupInput/InputGroupInput.js, packages/react-impression/src/components/InputGroupInput/README.md
=> Docs input input group

packages/react-impression/src/components/Dropdown/Dropdown.js, packages/react-impression/src/components/Dropdown/README.md, packages/react-impression/src/components/DropdownMenu/DropdownMenu.js, packages/react-impression/src/components/DropdownMenu/README.md, packages/react-impression/src/components/DropdownMenuDivider/DropdownMenuDivider.js, packages/react-impression/src/components/DropdownMenuDivider/README.md, packages/react-impression/src/components/DropdownMenuItem/DropdownMenuItem.js, packages/react-impression/src/components/DropdownMenuItem/README.md, packages/react-impression/src/components/DropdownTrigger/DropdownTrigger.js, packages/react-impression/src/components/DropdownTrigger/README.md
- Dropdown
- DropdownMenu
- DropdownMenuDivider
- DropdownMenuItem
- DropdownTrigger
=> [ADD] dropdown

packages/react-impression/src/components/FlexItem/README.md
=> [flex] flex相关重复示例删除 #56

packages/react-impression/src/components/Badge/Badge.js, packages/react-impression/src/components/Badge/README.md
=> Add docs of Badge #51

packages/react-impression/src/components/ListGroup/ListGroup.js, packages/react-impression/src/components/ListGroup/README.md, packages/react-impression/src/components/ListGroupItem/ListGroupItem.js, packages/react-impression/src/components/ListGroupItem/README.md
=> Docs ListGroup #58

packages/react-impression/src/components/Split/README.md, packages/react-impression/src/components/Split/Split.js
=> Docs Split #60

packages/react-impression/src/components/Timeline/README.md, packages/react-impression/src/components/Timeline/Timeline.js, packages/react-impression/src/components/TimelineItem/README.md, packages/react-impression/src/components/TimelineItem/TimelineItem.js
=> Docs Timeline #61

packages/react-impression/src/components/DatePicker/DatePicker.js, packages/react-impression/src/components/DatePicker/README.md
=> Docs datepicker

packages/react-impression/src/components/Collapse/README.md, packages/react-impression/src/components/CollapseBody/README.md, packages/react-impression/src/components/CollapseTitle/README.md
=> docs collapse

packages/react-impression/src/components/Calendar/Calendar.js, packages/react-impression/src/components/Calendar/README.md
=> docs calendar

packages/react-impression/src/components/Confirm/Confirm.js, packages/react-impression/src/components/Notice/Notice.js
=> Fix TypeError

packages/react-impression/rsg/config.js, packages/react-impression/rsg/styles.js, packages/react-impression/rsg/theme.js
=> Change style of usage

.travis.yml, README.md, package.json, packages/react-impression-website/package.json, packages/react-impression-website/rsg/config.js, packages/react-impression-website/rsg/styles.js, packages/react-impression-website/rsg/webpackConfig.js, packages/react-impression/src/components/Card/README.md, packages/react-impression/src/components/Image/README.md
=> Build and deploy website automatically

packages/react-impression/package.json, packages/react-impression/src/styles/_variables.scss, packages/react-impression/src/styles/index.scss, yarn.lock
=> Add support of px to rem

packages/react-impression/src/components/DatePicker/README.md
=> fix_datepicker_readme

packages/react-impression-website/rsg/webpackConfig.js
=> Optimize architecture

packages/react-impression/src/components/Calendar/README.md
=> fix_calendar_readme

packages/react-impression/package.json, packages/react-impression/src/components/Tag/README.md, packages/react-impression/src/components/Tag/Tag.js, packages/react-impression/src/styles/_variables.scss, packages/react-impression/src/styles/index.scss, packages/react-impression/src/styles/mixins/_tag.scss, packages/react-impression/src/styles/variables/_tag.scss, yarn.lock
=> Update style of Tag

.travis.yml, scripts/deploy.js
=> Auto deploy every pull request

package.json, scripts/deploy.js, yarn.lock
=> Auto add link to PR

packages/react-impression/src/styles/modules/_select.scss
=> [fix] fix select合并到next分支后，样式错乱问题

packages/react-impression/src/components/ButtonToolbar/README.md
=> fix eventkey

packages/react-impression-website/rsg/styles.js
=> fix props table

packages/react-impression/src/components/ListGroup/README.md
=> ListGroup示例汉化

packages/react-impression/src/components/Nav/Nav.js, packages/react-impression/src/components/Nav/README.md, packages/react-impression/src/components/NavItem/NavItem.js, packages/react-impression/src/styles/modules/_nav.scss, packages/react-impression/src/styles/variables/_nav.scss
=> Enhance nav

packages/react-impression/src/components/Pagination/Pagination.js, packages/react-impression/src/styles/modules/_pagination.scss
=> [enhance] pagination onSelect触发时机

packages/react-impression/src/components/Attention/Attention.js, packages/react-impression/src/components/Attention/README.md, packages/react-impression/src/styles/mixins/_attention.scss, packages/react-impression/src/styles/modules/_attention.scss, packages/react-impression/src/styles/variables/_attention.scss, packages/react-impression/src/styles/variables/_message.scss
1. Attention样式与Message统一
2. 调整AttentionLink样式
3. 字体大小调整为14px
=> Attention视觉走查

packages/react-impression/src/components/ButtonGroup/README.md, packages/react-impression/src/components/Card/README.md, packages/react-impression/src/components/CardBlock/README.md, packages/react-impression/src/components/CardFooter/README.md, packages/react-impression/src/components/CardHeader/README.md, packages/react-impression/src/components/Input/README.md, packages/react-impression/src/components/InputGroup/README.md, packages/react-impression/src/components/InputGroupAddon/README.md, packages/react-impression/src/components/InputGroupButton/README.md, packages/react-impression/src/styles/modules/_button-group.scss, packages/react-impression/src/styles/modules/_forms.scss, packages/react-impression/src/styles/modules/_input-group.scss, packages/react-impression/src/styles/modules/_popover.scss, packages/react-impression/src/styles/variables/_button.scss, packages/react-impression/src/styles/variables/_input.scss
fix Card InputGroup Form的ui走查样式
=> Wjeek fix ui

.npmrc, README.md, packages/react-impression-website/docs/Introduction.md, packages/react-impression-website/rsg/config.js, packages/react-impression/gulpfile.js, packages/react-impression/package.json, yarn.lock
=> Fix problems of release

packages/react-impression/src/components/DatePicker/DatePicker.js, packages/react-impression/src/components/DatePicker/README.md, packages/react-impression/src/styles/modules/_datepicker.scss, packages/react-impression/src/styles/variables/_datepicker.scss
1. 周末的文字颜色为浅灰色
2. 星期、日期的高度为40px
3. 选择年的纵向间距为20px
=> Datepicker视觉走查问题

packages/react-impression-website/rsg/components/StyleGuideRenderer.js, packages/react-impression-website/rsg/config.js, packages/react-impression-website/rsg/styles.js, packages/react-impression-website/rsg/theme.js
=> fix styleguide color

packages/react-impression/src/styles/variables/_button.scss
=> fix button height

packages/react-impression-website/rsg/config.js, packages/react-impression-website/rsg/styles.js, packages/react-impression-website/rsg/theme.js, yarn.lock
=> Optimize display of sidebar

packages/react-impression/src/components/Nav/Nav.js, packages/react-impression/src/components/Nav/README.md
=> [fix] 修正nav activekey 为0 时，不生效问题

packages/react-impression/src/components/Pagination/Pagination.js, packages/react-impression/src/components/Pagination/README.md
close #234 
1. totalPage为0时，默认显示1页
2. 分页组件文字居中
=> Pagination问题修复

packages/react-impression/src/styles/modules/_sidebar.scss, packages/react-impression/src/styles/variables/_sidebar.scss
=> Sidebar样式问题修复

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js
=> Fix select

packages/react-impression/src/components/Modal/Modal.js
=> fix isopen

packages/react-impression/src/components/Confirm/Confirm.js
=> fix confirm button

packages/react-impression/src/components/Button/Button.js
=> fix default props

packages/react-impression/src/components/Calendar/Calendar.js, packages/react-impression/src/components/Calendar/README.md
=> fix calendar readme

packages/react-impression-examples/src/app/components/Sidebar.js, packages/react-impression-examples/src/app/components/Sidebar.module.scss, packages/react-impression-examples/src/app/styles/_variables.scss, packages/react-impression-examples/src/index.html
=> fix sidebar & icon

packages/react-impression/src/components/Form/README.md
=> fix lineheight

packages/react-impression/src/styles/modules/_checkbox.scss
=> fix indeterminate

packages/react-impression/src/styles/variables/_button.scss, packages/react-impression/src/styles/variables/_input.scss
=> fix button input height

packages/react-impression/src/components/Input/Input.js
=> Input日期类型支持size属性

packages/react-impression/src/styles/modules/_input.scss
=> Input组件对齐的问题

packages/react-impression/src/components/Table/Table.js, packages/react-impression/src/styles/modules/_table.scss
=> [FIX] 修复table无数据情况下空白状态

.travis.yml, CHANGELOG.md, packages/react-impression-website/rsg/config.js, packages/react-impression/src/components/Input/Input.js, packages/react-impression/src/components/Popover/Popover.js, packages/react-impression/src/components/Table/Table.js, packages/react-impression/src/styles/modules/_checkbox.scss, packages/react-impression/src/styles/modules/_input.scss, packages/react-impression/src/styles/modules/_table.scss, packages/react-impression/src/styles/variables/_button.scss, packages/react-impression/src/styles/variables/_input.scss
* Add placeholder for github pages
* A 新增2.0发版记录
* Switch to branch master
* F 添加详情跳转链接
* fix indeterminate (#307)
* fix button input height (#306)
* F Input日期类型支持size属性 (#305)
* F input组件对齐的问题 (#304)
* [FIX] 修复table无数据情况下空白状态 (#301)
* [FIX] 修复table无数据情况下空白状态
* [fix] fix readme
* fix datepicker example (#310)
* fix popover (#309)
* Rename file
* Change title
=> 新增2.0发版记录 (#268)

packages/react-impression/src/components/Sidebar/README.md, packages/react-impression/src/styles/modules/_sidebar.scss
=> Sidebar组件样式的问题

packages/react-impression/src/components/DatePicker/DatePicker.js, packages/react-impression/src/components/Input/Input.js, packages/react-impression/src/styles/modules/_datepicker.scss, packages/react-impression/src/styles/variables/_datepicker.scss
close #253 #263 
1. 点击其他部分关闭datepicker
2. 空间不足自动调整datepicker位置
=> Datepicker fix

packages/react-impression/src/components/Select/README.md, packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js, packages/react-impression/src/components/SelectOptionGroup/SelectOptionGroup.js
=> E select(selectoption异步渲染引发的问题以及toLowerCase问题)

packages/react-impression/src/components/Nav/README.md, packages/react-impression/src/components/NavItem/README.md, packages/react-impression/src/components/NavLink/README.md
=> [E] NavLink示例指向NavItem

packages/react-impression/src/components/Upload/Upload.js, packages/react-impression/src/styles/modules/_upload.scss, packages/react-impression/src/styles/variables/_upload.scss
close #275 
1. 完善 组件的属性描述
2. 修复 preview模式下，改变组件尺寸后样式错乱的问题
=> Upload fix

packages/react-impression-examples/src/app/components/Sidebar.js, packages/react-impression-examples/src/form/components/Counter.js, packages/react-impression-examples/src/form/container.js, packages/react-impression-examples/src/form/container.module.scss, packages/react-impression-examples/src/form/containers/ChangePassword.js, packages/react-impression-examples/src/form/containers/CreateOrder.js, packages/react-impression-examples/src/form/containers/CreateOrder.module.scss, packages/react-impression-examples/src/form/index.js, packages/react-impression-examples/src/routes.js, packages/react-impression/src/components/Form/README.md
=> Wjeek add form example

packages/react-impression/src/components/Nav/Nav.js, packages/react-impression/src/components/Nav/README.md
=> [FIX] 修复Nav不受控

packages/react-impression/src/styles/variables/_table.scss
=> [FIX] 修复font-size过小时，table header的border消失问题

packages/react-impression/src/components/Navbar/Navbar.js
=> Add support for custom styles of Navbar

packages/react-impression/src/components/Sidebar/README.md, packages/react-impression/src/styles/modules/_sidebar.scss
=> 侧边栏NavItem作为一级菜单的样式

packages/react-impression/src/components/Nav/Nav.js, packages/react-impression/src/components/NavItem/NavItem.js
=> NavItem点击事件响应

packages/react-impression/src/components/Select/README.md, packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js, packages/react-impression/src/styles/modules/_select.scss
=> 更改selectOption弹出方式，修复table下select被遮挡问题，filterMethod支持实时搜索

packages/react-impression/src/components/Table/Table.js, packages/react-impression/src/components/TableBody/TableBody.js
=> [FIX] 修复columns不能动态更新问题

packages/react-impression/src/styles/variables/_zindex.scss
=> [fix] confirm-zIndex

packages/react-impression/src/components/Table/README.md, packages/react-impression/src/components/Table/Table.js, packages/react-impression/src/components/TableBody/TableBody.js, packages/react-impression/src/components/TableHead/TableHead.js, packages/react-impression/src/styles/modules/_table.scss
=> [FIX] 修复带右边固定项时，table过长时格式错乱问题

packages/react-impression/src/components/Select/Select.js
=> [fix] v2.0.3 fix select search下icon

CHANGELOG.md
=> changelog 2.0.2

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/styles/modules/_select.scss
=> [fix] select -width

packages/react-impression/src/components/DatePicker/DatePicker.js, packages/react-impression/src/components/Input/Input.js, packages/react-impression/src/styles/modules/_datepicker.scss
close #360 
1. Input中popper定位使用fixed
2. 开启gpu加速
3. 修改datepicker，多外包一层div，实现开启gpu加速情况下保留显示的动画效果
=> 修复date类型Input被遮挡

packages/react-impression-examples/src/overview/components/Filter.js, packages/react-impression-examples/src/overview/components/Filter.module.scss
=> Wjeek fix example

packages/react-impression/src/components/DatePicker/README.md, packages/react-impression/src/components/Input/README.md, packages/react-impression/src/styles/modules/_forms.scss, packages/react-impression/src/styles/modules/_table.scss, packages/react-impression/src/styles/variables/_input.scss
=> Input宽度固定16rem

CHANGELOG.md, packages/react-impression/src/components/Content/Content.js
=> Wjeek remove animation 353

packages/react-impression/src/components/Dropdown/README.md, packages/react-impression/src/components/ListGroup/README.md, packages/react-impression/src/components/Split/README.md
=> fix void(0)

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js, packages/react-impression/src/styles/modules/_select.scss
=> [fix] select popover优化

babel.config.js, package.json, packages/react-impression/package.json, packages/react-impression/src/components/Table/README.md, packages/react-impression/src/components/Table/Table.js, yarn.lock
=> [fix] Table 组件的 column prop，Header 属性的值不能是组件

packages/react-impression/src/styles/_variables.scss, packages/react-impression/src/styles/modules/_animation.scss, packages/react-impression/src/styles/variables/_page.scss, packages/react-impression/src/styles/variables/_zindex.scss
=> fix zindex

packages/react-impression/package.json, packages/react-impression/src/components/Tooltip/Tooltip.js, packages/react-impression/src/styles/modules/_tooltip.scss
=> Fix tooltip wrapper

packages/react-impression/src/components/Table/Table.js
=> [fix] classname给到最外面div，满足外面可以控制overflow hidden取消

packages/react-impression/package.json, packages/react-impression/src/components/Tooltip/Tooltip.js, packages/react-impression/src/styles/modules/_tooltip.scss, packages/react-impression/src/styles/variables/_tooltip.scss
=> Revert tooltip

packages/react-impression/src/styles/variables/_button.scss
=> fix button color

packages/react-impression/src/styles/modules/_select.scss, packages/react-impression/src/styles/variables/_select.scss
=> [fix] 给selectOption设置默认行高

packages/react-impression/src/components/Select/Select.js
=> [fix] select选中回调参数

packages/react-impression/src/components/Card/README.md
=> fix card example

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/styles/modules/_select.scss
=> [U] 优化select滚动条

packages/react-impression/src/components/Input/Input.js, packages/react-impression/src/components/Input/README.md
=> fix input校验

packages/react-impression/src/components/Popover/Popover.js
=> popover = null

packages/react-impression/src/components/Select/Select.js
=> [fix] multiple select placeholder

packages/react-impression/src/components/ButtonGroup/ButtonGroup.js
=> [fix] btngroup activekey

packages/react-impression/src/components/SidebarBody/SidebarBody.js
=> Sidebar组件更新Scroll报错问题

packages/react-impression/src/components/Table/README.md, packages/react-impression/src/components/Table/Table.js, packages/react-impression/src/styles/modules/_table.scss
=> [ADD] table无数据时，提示文字可配置

packages/react-impression/src/components/Pagination/Pagination.js, packages/react-impression/src/components/Pagination/README.md, packages/react-impression/src/styles/modules/_pagination.scss, packages/react-impression/src/styles/variables/_pagination.scss
=> 分页组件支持快速跳转

packages/react-impression/src/components/Select/README.md, packages/react-impression/src/components/Select/Select.js
=> [ADD] clearable select

packages/react-impression/src/components/Select/Select.js
=> [[fix] select perfect scrollbar

packages/react-impression/src/components/Table/Table.js
=> [fix] table-update

packages/react-impression/src/styles/modules/_forms.scss
=> U updte form-group label

packages/react-impression/src/components/Pagination/Pagination.js
=> F 引入Input组件

packages/react-impression/src/components/Table/Table.js
=> [fix] 多选table木偶组件判断

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js
=> Fix select search

packages/react-impression/src/components/Table/README.md
=> U table readme

packages/react-impression/src/styles/modules/_select.scss
=> F safari下input无法选中问题

packages/react-impression/src/components/Table/README.md, packages/react-impression/src/styles/variables/_button.scss, packages/react-impression/src/styles/variables/_colors.scss
=> Update ui design

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js, packages/react-impression/src/components/SelectOptionGroup/SelectOptionGroup.js
=> F selectoption内容为空判断

packages/react-impression/src/components/Notice/Notice.js, packages/react-impression/src/components/Notification/Notification.js
=> 【BF】修复466issue，notification组件鼠标移入时计时器移除提示不消失，鼠标移开时计时器重新开始duration时间后提示消失

packages/react-impression/src/components/Select/Select.js
=> F 非受控Select的选中值，错误被清空现象

packages/react-impression/src/components/Upload/Upload.js, packages/react-impression/src/styles/modules/_upload.scss, packages/react-impression/src/styles/variables/_upload.scss
=> 图片上传支持大图预览

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SidebarBody/SidebarBody.js, packages/react-impression/src/components/TimeSelect/TimeSelect.js
修复异步初始化 perfect-scrollbar 时定时器未清除导致的报错
https://github.com/mdbootstrap/perfect-scrollbar/blob/master/src/index.js#L45
=> F fix init perfect-scrollbar

packages/react-impression/src/components/Upload/Upload.js, packages/react-impression/src/styles/modules/_upload.scss
1、新增fileName、disabled属性
2、修复Uncaught TypeError: Cannot read property 'name' of undefined报错
=> upload add fileName and disabled props

packages/react-impression/src/components/Select/README.md, packages/react-impression/src/components/Select/Select.js
=> select support remote search

packages/react-impression/src/styles/modules/_select.scss
=> U 修改下拉框icon样式

packages/react-impression/src/components/Collapse/Collapse.js, packages/react-impression/src/components/Collapse/README.md, packages/react-impression/src/components/CollapseTitle/CollapseTitle.js, packages/react-impression/src/components/NavItem/NavItem.js, packages/react-impression/src/styles/modules/_collapse.scss, packages/react-impression/src/styles/modules/_sidebar.scss, packages/react-impression/src/styles/variables/_sidebar.scss
- `Collapse` 组件增加 `subCollapse` 属性，用于实现三级菜单；
- 修改部分 `style` 样式文件，用于实现三级菜单；
- 增加 `Collapse`  的使用示例；
=> Feat: Collapse add the props of subCollapse

packages/react-impression/src/components/Image/Image.js
=> fix 特殊字符会导致图片不显示

packages/react-impression-website/package.json, packages/react-impression-website/rsg/webpackConfig.js, packages/react-impression/src/styles/variables/_grid.scss, yarn.lock
1、文档库依赖node-sass替换为sass
2、升级sass-loader
=> refactor replace node-sass to sass

packages/react-impression/src/styles/_mixins.scss, packages/react-impression/src/styles/_variables.scss, packages/react-impression/src/styles/mixins/_text-hide.scss, packages/react-impression/src/styles/mixins/_text-truncate.scss, packages/react-impression/src/styles/mixins/_typography.scss, packages/react-impression/src/styles/modules/_navbar.scss, packages/react-impression/src/styles/modules/_type.scss, packages/react-impression/src/styles/utilities/_text.scss, packages/react-impression/src/styles/variables/_card.scss, packages/react-impression/src/styles/variables/_confirm.scss, packages/react-impression/src/styles/variables/_headings.scss, packages/react-impression/src/styles/variables/_modal.scss, packages/react-impression/src/styles/variables/_typography.scss
1、去除无用代码
2、添加文字规范变量、通过mixin计算line-height
3、添加关于文字的文档说明
=> feat 添加文字段落规范

packages/react-impression/src/components/Input/Input.js, packages/react-impression/src/components/Input/README.md, packages/react-impression/src/styles/mixins/_forms.scss, packages/react-impression/src/styles/modules/_forms.scss, packages/react-impression/src/styles/modules/_input-group.scss, packages/react-impression/src/styles/modules/_input.scss, packages/react-impression/src/styles/modules/_select.scss, packages/react-impression/src/styles/modules/_upload.scss, packages/react-impression/src/styles/variables/_colors.scss, packages/react-impression/src/styles/variables/_input.scss, packages/react-impression/src/styles/variables/_select.scss, packages/react-impression/src/utils/system.js
1、去除 Input pill 属性
2、优化 Input 中点击组件外收起下拉内容的逻辑
3、Input组件样式重构
4、新增 Input组件 addonBefore、addonAfter 属性，添加自定义图标
5、删除 无用的mixin：form-control-validation、input-size
6、更新 Input组件的文档说明内容
=> Refactor input

packages/react-impression/src/components/Button/README.md, packages/react-impression/src/components/Input/README.md, packages/react-impression/src/components/InputGroup/InputGroup.js, packages/react-impression/src/components/InputGroup/README.md, packages/react-impression/src/components/InputGroupAddon/README.md, packages/react-impression/src/components/InputGroupInput/InputGroupInput.js, packages/react-impression/src/components/Upload/README.md, packages/react-impression/src/components/Upload/Upload.js, packages/react-impression/src/styles/modules/_input-group.scss, packages/react-impression/src/styles/modules/_upload.scss, packages/react-impression/src/styles/variables/_upload.scss, packages/react-impression/src/styles/variables/_zindex.scss
1、重构 Upload组件，修复多文件上传缺陷、优化样式
2、优化 按钮和输入框组合的样式
=> Feat input & button & upload

packages/react-impression/src/components/Table/Table.js
[issue ticket](https://github.com/NewDadaFE/react-impression/issues/509)
=> fix: table crash when update rowselection

packages/react-impression/src/components/Modal/Modal.js, packages/react-impression/src/components/Search/README.md, packages/react-impression/src/components/Search/Search.js, packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/Trigger/README.md, packages/react-impression/src/components/Trigger/Trigger.js, packages/react-impression/src/styles/modules/_search.scss, packages/react-impression/src/styles/modules/_select.scss, packages/react-impression/src/styles/modules/_trigger.scss
fix search组件样式和交互
fix trigger弹出定位不准确的问题
fix trigger样式问题
=> Fix 2.1.2 2

packages/react-impression/package.json, packages/react-impression/src/components/Popover/Popover.js, packages/react-impression/src/components/Popover/README.md, packages/react-impression/src/components/Select/README.md, packages/react-impression/src/components/Trigger/README.md, packages/react-impression/src/components/Trigger/Trigger.js, packages/react-impression/src/styles/modules/_animation.scss, packages/react-impression/src/styles/modules/_popover.scss, packages/react-impression/src/styles/modules/_trigger.scss, packages/react-impression/src/styles/modules/_utilities.scss, packages/react-impression/src/styles/utilities/_shadow.scss, packages/react-impression/src/styles/variables/_common.scss, packages/react-impression/src/styles/variables/_popover.scss
1、优化 Trigger支持自定义offset、箭头、描边、阴影
2、重构 Popover组件，使用Trigger实现
3、删除 popper.js
=> feat Trigger支持自定义offset、箭头、描边、阴影

packages/react-impression/src/components/Trigger/Trigger.js
修复 showAction为hover时，鼠标快速移动到弹出层，弹出层消失的问题
=> fix trigger 显示事件为hover下的交互

CHANGELOG.md, package.json, packages/react-impression/package.json, yarn.lock
修改 `@emotion/is-prop-valid` 依赖的安装位置
=> fix 安装必须的依赖

CHANGELOG.md, packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js
- feat:增加 _SelectOption_ 组件被选中后是否可删除属性;
- fix:修复 _Select_ 组件，被选中选项为disabled时可删除问题;
=> Feat multiple select

packages/react-impression/src/components/Search/README.md, packages/react-impression/src/components/Search/Search.js, packages/react-impression/src/components/TimeSelect/TimeSelect.js, packages/react-impression/src/styles/modules/_forms.scss, packages/react-impression/src/styles/modules/_timeSelect.scss, packages/react-impression/src/styles/variables/_timeSelect.scss
1、修复 Form下面用Search组件宽度没有撑满
2、修复 Search组件受控 初始值不生效
3、修复 TimeSelect 面板上的样式名称没有.dada前缀，导致跟项目的全局样式.title冲突
=> Fix 3.0.0 beta.1

packages/react-impression/src/utils/system.js
=> fix:修复contains报错

packages/react-impression/src/components/Breadcrumb/Breadcrumb.js, packages/react-impression/src/components/Breadcrumb/README.md, packages/react-impression/src/styles/modules/_breadcrumb.scss, packages/react-impression/src/styles/variables/_breadcrumb.scss
Breadcrumb组件的优化
1.样式优化
2.最多支持四级路径，超出收起弹窗展示
=> 0517breadcrumb

packages/react-impression/src/components/Menu/Menu.js, packages/react-impression/src/components/Menu/components/Content.js, packages/react-impression/src/styles/modules/_menu.scss
=> fix: interactive optimization of menu

packages/react-impression/src/components/DatePicker/DatePicker.js, packages/react-impression/src/components/DatePicker/README.md
1.修复DatePicker 受控时 修改value，控件面板没有更新的问题
=> Fix 20211206

packages/react-impression/src/components/Select/Select.js
=> select支持下拉加载

packages/react-impression/src/components/CheckboxGroup/CheckboxGroup.js
=> fix:修复 `CheckBoxGroup` 默认值问题

CHANGELOG.md, package.json, packages/react-impression/package.json
=> v3.0.0-alpha.15

packages/react-impression/src/components/Select/README.md
=> 增加select-onScrollBottom使用示例

packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/Trigger/Trigger.js
select add container and outsideDisabled
=> add: select add container and outsideDisabled

CHANGELOG.md, package.json, packages/react-impression/package.json, packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/components/SelectOption/SelectOption.js
version 3.0.0-alpha.19
Co-authored-by: zhangjuan <zhangjuan@DDZV1GGL414>
fix select null/0和空字符串的显示
fix select null/0和空字符串的显示
v3.0.0-alpha.20
fix select null/0和空字符串的显示
=> Version3.0.0 alpha.19 (#675)

CHANGELOG.md, packages/react-impression/src/components/Menu/Menu.js, packages/react-impression/src/components/Table/Table.js, packages/react-impression/src/components/TreeSelect/TreeSelect.js, packages/react-impression/src/styles/modules/_treeSelect.scss
- fix **Table** 错行问题
- 新增 **Menu** defaultCollapsed 属性，控制默认折叠状态
- fix **TreeSelect** 边框样式问题以及默认 switcherIcon
=> fix table错行问题+feat menu默认折叠状态prop + fix treeSelect样式问题

packages/react-impression/src/components/Table/Table.js, packages/react-impression/src/components/TableBody/TableBody.js, packages/react-impression/src/components/TableHead/TableHead.js
=> fix table默认宽问题

packages/react-impression/src/components/Select/README.md, packages/react-impression/src/components/Select/Select.js, packages/react-impression/src/styles/modules/_select.scss
=> fix readme
